exports.seed = (knex) => {
  return knex('found').insert([
    {
      id: 1,
      species: 'Dog',
      photo: '/images/dogs/dog3.jpg',
      user_id: '10',
      user_name: 'Emily',
      user_contact: 'emilylovesdogs@gmail.com',
    },
    {
      id: 2,
      species: 'Dog',
      photo: '/images/dogs/dog4.jpg',
      user_id: '20',
      user_name: 'Belle',
      user_contact: 'belleiscool@hotmail.com',
    },
    {
      id: 3,
      species: 'Cat',
      photo: '/images/cats/cat3.jpg',
      user_id: '30',
      user_name: 'Ben',
      user_contact: 'bentheplumber@gmail.com',
    },
    {
      id: 4,
      species: 'Dog',
      photo: '/images/dogs/dog5.jpg',
      user_id: '40',
      user_name: 'Jasper',
      user_contact: 'jaspertakesphotos@gmail.com',
    },
    {
      id: 5,
      species: 'Cat',
      photo: '/images/cats/cat4.jpg',
      user_id: '50',
      user_name: 'Sarah',
      user_contact: 'sarah_smith@hotmail.com',
    },
    {
      id: 6,
      species: 'Cat',
      photo: '/images/cats/cat5.jpg',
      user_id: '60',
      user_name: 'Lisa',
      user_contact: 'lisa_575@gmail.com',
    },
    {
      id: 7,
      species: 'Dog',
      photo: '/images/dogs/dog6.jpg',
      user_id: '70',
      user_name: 'Andy',
      user_contact: 'buzzandwoody@hotmail.com',
    },
  ])
}
